# Generated by Django 5.0.6 on 2024-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calimaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifer_cal', models.CharField(default='Unknown', max_length=20)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(default='Pending', max_length=20)),
                ('fecha_modificacion', models.DateTimeField()),
                ('usuario', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_externo', models.CharField(default='Unknown', max_length=20)),
                ('metodo', models.TextField(default='N/A')),
                ('respuesta', models.TextField(default='N/A')),
                ('agente', models.IntegerField(default=0)),
                ('fecha_de_registro_del_jugador', models.DateTimeField()),
            ],
            options={
                'db_table': 'CALIMACO',
            },
        ),
        migrations.CreateModel(
            name='GestionRW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('registro', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('bono', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('web_id', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('recarga', models.IntegerField()),
                ('bono_5_por_ciento', models.IntegerField()),
                ('promotor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GESTION_RW',
            },
        ),
    ]
