# Generated by Django 5.0.6 on 2024-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calimaco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_modificacion', models.DateTimeField()),
                ('usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cantidad', models.IntegerField()),
                ('id_externo', models.IntegerField()),
                ('metodo', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=255)),
                ('agente', models.IntegerField()),
                ('fecha_registro_jugador', models.DateTimeField()),
            ],
            options={
                'db_table': 'CALIMACO',
            },
        ),
        migrations.CreateModel(
            name='GestionRW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('registro', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('bono', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=20)),
                ('web_id', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('recarga', models.IntegerField()),
                ('bono_5_por_ciento', models.IntegerField()),
                ('promotor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GESTION_RW',
            },
        ),
    ]
