# Generated by Django 5.0.6 on 2024-06-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calimaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='Unknown', max_length=20)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(default='Pending', max_length=20)),
                ('fecha_modificacion', models.DateTimeField()),
                ('usuario', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_externo', models.CharField(default='Unknown', max_length=20)),
                ('respuesta', models.TextField(default='N/A')),
                ('agente', models.IntegerField(default=0)),
                ('fecha_de_registro_del_jugador', models.DateTimeField()),
            ],
            options={
                'db_table': 'CALIMACO',
            },
        ),
        migrations.CreateModel(
            name='GestionRW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.IntegerField()),
                ('Local', models.CharField(max_length=100)),
                ('Registro', models.DateTimeField()),
                ('Tipo', models.CharField(max_length=100)),
                ('Proveedor', models.CharField(max_length=100)),
                ('Bono', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Tipo_documento', models.CharField(max_length=10)),
                ('Numero_documento', models.CharField(max_length=20)),
                ('Web_id', models.IntegerField()),
                ('Cliente', models.CharField(max_length=255)),
                ('Recarga', models.IntegerField()),
                ('Bono_5_por_ciento', models.IntegerField()),
                ('Promotor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GESTION_RW',
            },
        ),
    ]
