# Generated by Django 5.0.6 on 2024-06-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recargas_Web', '0005_calimaco_cliente_alter_calimaco_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calimaco',
            old_name='Id',
            new_name='id',
        ),
    ]
