# Generated by Django 5.0.6 on 2024-06-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recargas_Web', '0006_rename_id_calimaco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calimaco',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
